[package]
name = "cpdb-rs"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[build-dependencies]
bindgen = "0.69"

[dependencies]
libc = "0.2"
thiserror = "1.0"
log = "0.4"
once_cell = "1.18"

[features]
frontend = []
backend = []