[package]
name = "cpdb-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
libc = "0.2"
thiserror = "1.0"
log = "0.4"
once_cell = "1.18"
crossbeam-channel = "0.5"
glib-sys = "0.19"

[build-dependencies]
bindgen = "0.69"
pkg-config = "0.3"

[features]
frontend = []
backend = []

[dev-dependencies]
tempfile = "3.10"